# Generated by Django 4.0.5 on 2022-06-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chech_In',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('amount_paid', models.CharField(max_length=10)),
                ('occupant_name', models.CharField(max_length=50)),
                ('occupant_email', models.EmailField(max_length=50)),
                ('occupant_occupation', models.CharField(max_length=50)),
                ('number_of_nights', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
            ],
        ),
    ]
