# Generated by Django 4.0.5 on 2022-06-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chech_in',
            name='end_date',
            field=models.DateField(default='1997-12-2'),
        ),
    ]
