# Generated by Django 4.0.5 on 2022-06-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_chech_in_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chech_in',
            name='serial_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
