# Generated by Django 4.0.5 on 2022-06-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_chech_in_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chech_in',
            name='serial_number',
        ),
    ]
